import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="#">DotAsk!</a>
        </h1>

        <p className={styles.description}>
          <a className={styles.a1} href="https://www.dotask.co/">dotask.co</a> is under construction, you can visit{' '}
          <a className={styles.a1} href="https://www.dotask.cc/">dotask.cc</a>
        </p>
        <div className={styles.grid}>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="#"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {'OpenSquare'}

        </a>
      </footer>
    </div>
  )
}
